services:
  postgres:
    image: postgres:17-alpine
    container_name: Project-DB
    ports:
      - "5432:5432"
    volumes:
      - project-volumes:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    networks:
      - project-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Project-API
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NODE_ENV: development
    depends_on:
      - postgres
    restart: always
    networks:
      - project-network

volumes:
  project-volumes:
    name: project-volumes

networks:
  project-network:
    external: true