services:
  postgres:
    image: postgres:17-alpine
    container_name: Project-DB
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_user -d your_database"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - project-volumes:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    networks:
      - project-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Project-API
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgresql://${POSTGRES_APP_USER}:${POSTGRES_APP_PASSWORD}@postgres:5432/${POSTGRES_DB}
      NODE_ENV: development
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - project-network

volumes:
  project-volumes:
    name: project-volumes

networks:
  project-network:
    external: true